name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install
        uses: actions/setup-go@v2
        run: GOOS=js GOARCH=wasm go build -o web/yourgame.wasm
        
      - run: cp $(go env GOROOT)/misc/wasm/wasm_exec.js ./web

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: web # The folder the action should deploy.